repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the ref you want to point at
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: check-merge-conflict
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.4
  hooks:
    - id: ruff-check
    - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        additional_dependencies: ['typer>=0.24.0', 'pyathena[pandas]>=3.30.0', 'types-pyyaml>=6.0.12.20260408', 'types-tqdm']

